<a href="https://cognitiveclass.ai"><img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DL0101EN-SkillsNetwork/images/IDSN-logo.png" width="400"> </a>

# Regression Models with Keras

Estimated time needed: **45** mins

## Introduction

## Objectives for this Notebook    
* How to use the Keras library to build a regression model
* Download and clean the data set
* Build a neural network
* Train and test the network

## Table of Contents

<div class="alert alert-block alert-info" style="margin-top: 20px">

<font size = 3>
    
1. <a href="#item31">Download and Clean the Data Set</a>  
2. <a href="#item32">Import Keras Packages</a>
3. <a href="#item33">Build a Neural Network</a>
4. <a href="#item34">Train and Test the Network</a>  

</font>
</div>

<a id="item31"></a>

## Download and Clean the  Data Set

Let's start by importing the <em>pandas</em> and the Numpy libraries.

In [ ]:
# All Libraries required for this lab are listed below. The libraries pre-installed on Skills Network Labs are commented. 
# If you run this notebook on a different environment, e.g. your desktop, you may need to uncomment and install certain libraries.
!pip install numpy==2.0.2
!pip install pandas==2.2.2
!pip install tensorflow_cpu==2.18.0

##### To use Keras, you will also need to install a backend framework – such as TensorFlow.

If you install TensorFlow 2.16 or above, it will install Keras by default.

We are using the CPU version of tensorflow since we are dealing with smaller datasets. 
You may install the GPU version of tensorflow on your machine to accelarate the processing of larger datasets

In [1]:
import pandas as pd
import numpy as np
import keras

import warnings
warnings.simplefilter('ignore', FutureWarning)

We will be playing around with the same dataset that we used in the videos.

<strong>The dataset is about the compressive strength of different samples of concrete based on the volumes of the different ingredients that were used to make them. Ingredients include:</strong>

* Cement
* Blast furnace slag
* Fly ash
* Water
* Superplasticizer
* Coarse aggregate
* Fine aggregate

Let's download the data and read it into a <em>pandas</em> dataframe.

In [2]:
filepath='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv'
concrete_data = pd.read_csv(filepath)

concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

So the first concrete sample has 540 cubic meter of cement, 0 cubic meter of blast furnace slag, 0 cubic meter of fly ash, 162 cubic meter of water, 2.5 cubic meter of superplaticizer, 1040 cubic meter of coarse aggregate, 676 cubic meter of fine aggregate. Such a concrete mix which is 28 days old, has a compressive strength of 79.99 MPa.

#### Let's check how many data points we have

In [3]:
concrete_data.shape

(1030, 9)

So, there are approximately 1000 samples to train our model on. Because of the few samples, we have to be careful not to overfit the training data.

Let's check the dataset for any missing values.

In [4]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [5]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

The data looks very clean and is ready to be used to build our model.

#### Split data into predictors and target

The target variable in this problem is the concrete sample strength. Therefore, our predictors will be all the other columns.

In [6]:
concrete_data_columns = concrete_data.columns

In [7]:
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

<a id="item2"></a>

Let's do a quick sanity check of the predictors and the target dataframes.

In [8]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [9]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

Finally, the last step is to normalize the data by substracting the mean and dividing by the standard deviation.

In [10]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

Let's save the number of predictors to *n_cols* since we will need this number when building our network.

In [11]:
n_cols = predictors_norm.shape[1] # number of predictors

<a id="item1"></a>

<a id='item32'></a>

##  Import Keras Packages

##### Let's import the rest of the packages from the Keras library that we will need to build our regression model.

In [12]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input

<a id='item33'></a>

## Build a Neural Network

Let's define a function that defines our regression model for us so that we can conveniently call it to create our model.

In [13]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Input(shape=(n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

The above function create a model that has two hidden layers, each of 50 hidden units.

<a id="item4"></a>

## Train and Test the Network

Let's call the function now to create our model.

In [14]:
# build the model
model = regression_model()

Next, we will train and test the model at the same time using the *fit* method. We will leave out 30% of the data for validation and we will train the model for 100 epochs.

In [15]:
# fit the model
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 5s - 239ms/step - loss: 1621.8883 - val_loss: 1129.3257
Epoch 2/100
23/23 - 0s - 16ms/step - loss: 1483.9781 - val_loss: 1004.6857
Epoch 3/100
23/23 - 1s - 32ms/step - loss: 1258.4484 - val_loss: 813.1140
Epoch 4/100
23/23 - 1s - 24ms/step - loss: 932.8364 - val_loss: 570.5081
Epoch 5/100
23/23 - 0s - 16ms/step - loss: 572.9907 - val_loss: 351.3390
Epoch 6/100
23/23 - 0s - 16ms/step - loss: 329.6907 - val_loss: 233.0324
Epoch 7/100
23/23 - 0s - 18ms/step - loss: 247.1584 - val_loss: 204.8428
Epoch 8/100
23/23 - 0s - 18ms/step - loss: 224.9962 - val_loss: 198.0535
Epoch 9/100
23/23 - 1s - 25ms/step - loss: 213.6872 - val_loss: 189.1286
Epoch 10/100
23/23 - 1s - 24ms/step - loss: 205.0800 - val_loss: 183.2307
Epoch 11/100
23/23 - 0s - 21ms/step - loss: 196.9876 - val_loss: 176.7417
Epoch 12/100
23/23 - 0s - 15ms/step - loss: 191.0583 - val_loss: 171.9843
Epoch 13/100
23/23 - 0s - 14ms/step - loss: 184.2993 - val_loss: 168.3942
Epoch 14/100
23/23 - 0s - 16ms/step - loss: 179.5965 - val_loss: 166.9494
Epoch 15/100
23/23 - 0s - 20ms/step - loss: 175.0815 - val_loss: 162.4043
Epoch 16/100
23/23 - 1s - 22ms/step - loss: 170.6767 - val_loss: 159.2505
Epoch 17/100
23/23 - 0s - 17ms/step - loss: 167.5752 - val_loss: 158.6351
Epoch 18/100
23/23 - 0s - 21ms/step - loss: 163.3526 - val_loss: 156.5741
Epoch 19/100
23/23 - 0s - 14ms/step - loss: 160.5274 - val_loss: 155.1472
Epoch 20/100
23/23 - 1s - 28ms/step - loss: 158.2060 - val_loss: 154.5109
Epoch 21/100
23/23 - 1s - 23ms/step - loss: 154.9191 - val_loss: 153.0971
Epoch 22/100
23/23 - 1s - 25ms/step - loss: 152.2718 - val_loss: 149.2277
Epoch 23/100
23/23 - 0s - 17ms/step - loss: 150.0863 - val_loss: 150.8537
Epoch 24/100
23/23 - 0s - 17ms/step - loss: 147.5722 - val_loss: 149.8217
Epoch 25/100
23/23 - 0s - 15ms/step - loss: 145.2159 - val_loss: 149.0111
Epoch 26/100
23/23 - 0s - 13ms/step - loss: 143.5820 - val_loss: 147.8615
Epoch 27/100
23/23 - 0s - 11ms/step - loss: 141.7569 - val_loss: 149.0440
Epoch 28/100
23/23 - 0s - 13ms/step - loss: 140.7822 - val_loss: 147.7638
Epoch 29/100
23/23 - 0s - 22ms/step - loss: 138.3120 - val_loss: 149.2500
Epoch 30/100
23/23 - 0s - 14ms/step - loss: 136.8905 - val_loss: 145.5821
Epoch 31/100
23/23 - 0s - 13ms/step - loss: 135.1121 - val_loss: 147.1519
Epoch 32/100
23/23 - 0s - 14ms/step - loss: 133.4180 - val_loss: 147.7087
Epoch 33/100
23/23 - 0s - 15ms/step - loss: 131.5773 - val_loss: 147.4826
Epoch 34/100
23/23 - 0s - 13ms/step - loss: 129.7162 - val_loss: 146.0844
Epoch 35/100
23/23 - 0s - 14ms/step - loss: 128.0662 - val_loss: 146.2189
Epoch 36/100
23/23 - 0s - 13ms/step - loss: 127.6579 - val_loss: 147.2059
Epoch 37/100
23/23 - 0s - 13ms/step - loss: 125.6164 - val_loss: 147.4088
Epoch 38/100
23/23 - 0s - 11ms/step - loss: 123.0393 - val_loss: 146.5241
Epoch 39/100
23/23 - 0s - 11ms/step - loss: 121.5301 - val_loss: 147.4593
Epoch 40/100
23/23 - 0s - 10ms/step - loss: 119.2151 - val_loss: 146.4617
Epoch 41/100
23/23 - 0s - 11ms/step - loss: 118.0525 - val_loss: 146.4236
Epoch 42/100
23/23 - 0s - 10ms/step - loss: 115.7185 - val_loss: 146.6518
Epoch 43/100
23/23 - 0s - 9ms/step - loss: 113.0380 - val_loss: 144.2110
Epoch 44/100
23/23 - 0s - 10ms/step - loss: 111.6517 - val_loss: 145.3261
Epoch 45/100
23/23 - 0s - 8ms/step - loss: 108.6965 - val_loss: 144.2574
Epoch 46/100
23/23 - 0s - 10ms/step - loss: 106.6549 - val_loss: 145.1439
Epoch 47/100
23/23 - 0s - 13ms/step - loss: 104.3630 - val_loss: 144.0038
Epoch 48/100
23/23 - 0s - 12ms/step - loss: 102.3872 - val_loss: 141.8616
Epoch 49/100
23/23 - 0s - 11ms/step - loss: 99.8733 - val_loss: 145.2265
Epoch 50/100
23/23 - 0s - 9ms/step - loss: 97.7388 - val_loss: 145.1211
Epoch 51/100
23/23 - 0s - 9ms/step - loss: 94.7371 - val_loss: 144.5211
Epoch 52/100
23/23 - 0s - 11ms/step - loss: 91.6079 - val_loss: 145.4609
Epoch 53/100
23/23 - 0s - 10ms/step - loss: 89.3217 - val_loss: 142.9438
Epoch 54/100
23/23 - 0s - 11ms/step - loss: 86.1111 - val_loss: 143.2810
Epoch 55/100
23/23 - 0s - 11ms/step - loss: 82.6403 - val_loss: 141.0395
Epoch 56/100
23/23 - 0s - 17ms/step - loss: 79.4984 - val_loss: 139.7549
Epoch 57/100
23/23 - 0s - 15ms/step - loss: 77.6353 - val_loss: 138.8457
Epoch 58/100
23/23 - 0s - 12ms/step - loss: 73.8336 - val_loss: 132.9697
Epoch 59/100
23/23 - 0s - 12ms/step - loss: 72.3640 - val_loss: 139.2034
Epoch 60/100
23/23 - 0s - 10ms/step - loss: 69.5842 - val_loss: 136.4494
Epoch 61/100
23/23 - 0s - 9ms/step - loss: 66.9882 - val_loss: 139.5690
Epoch 62/100
23/23 - 0s - 9ms/step - loss: 64.5010 - val_loss: 131.1608
Epoch 63/100
23/23 - 0s - 11ms/step - loss: 61.9425 - val_loss: 134.3567
Epoch 64/100
23/23 - 0s - 12ms/step - loss: 59.5347 - val_loss: 131.2270
Epoch 65/100
23/23 - 0s - 12ms/step - loss: 57.1431 - val_loss: 142.3382
Epoch 66/100
23/23 - 0s - 17ms/step - loss: 55.8591 - val_loss: 132.0996
Epoch 67/100
23/23 - 0s - 14ms/step - loss: 53.9601 - val_loss: 130.0543
Epoch 68/100
23/23 - 0s - 15ms/step - loss: 52.6064 - val_loss: 131.4873
Epoch 69/100
23/23 - 1s - 29ms/step - loss: 50.5218 - val_loss: 134.0278
Epoch 70/100
23/23 - 0s - 11ms/step - loss: 49.2961 - val_loss: 130.0926
Epoch 71/100
23/23 - 0s - 17ms/step - loss: 48.6772 - val_loss: 129.4278
Epoch 72/100
23/23 - 0s - 18ms/step - loss: 47.6333 - val_loss: 136.0761
Epoch 73/100
23/23 - 0s - 13ms/step - loss: 46.2677 - val_loss: 143.2840
Epoch 74/100
23/23 - 0s - 12ms/step - loss: 45.4184 - val_loss: 137.2834
Epoch 75/100
23/23 - 0s - 12ms/step - loss: 44.3309 - val_loss: 133.6678
Epoch 76/100
23/23 - 0s - 12ms/step - loss: 43.6984 - val_loss: 138.1130
Epoch 77/100
23/23 - 0s - 11ms/step - loss: 42.9453 - val_loss: 134.9122
Epoch 78/100
23/23 - 0s - 12ms/step - loss: 42.3240 - val_loss: 129.1899
Epoch 79/100
23/23 - 0s - 12ms/step - loss: 42.1834 - val_loss: 142.3448
Epoch 80/100
23/23 - 0s - 12ms/step - loss: 41.3613 - val_loss: 139.5378
Epoch 81/100
23/23 - 0s - 18ms/step - loss: 40.8112 - val_loss: 138.3427
Epoch 82/100
23/23 - 0s - 14ms/step - loss: 39.6214 - val_loss: 140.3904
Epoch 83/100
23/23 - 0s - 14ms/step - loss: 39.0441 - val_loss: 137.2248
Epoch 84/100
23/23 - 0s - 13ms/step - loss: 38.5748 - val_loss: 132.4230
Epoch 85/100
23/23 - 0s - 12ms/step - loss: 38.2111 - val_loss: 145.8941
Epoch 86/100
23/23 - 0s - 12ms/step - loss: 37.9227 - val_loss: 142.5444
Epoch 87/100
23/23 - 0s - 13ms/step - loss: 37.6613 - val_loss: 147.2321
Epoch 88/100
23/23 - 0s - 13ms/step - loss: 36.9987 - val_loss: 138.5317
Epoch 89/100
23/23 - 0s - 19ms/step - loss: 37.0336 - val_loss: 139.9866
Epoch 90/100
23/23 - 0s - 15ms/step - loss: 36.8184 - val_loss: 144.2225
Epoch 91/100
23/23 - 0s - 12ms/step - loss: 35.7040 - val_loss: 146.8239
Epoch 92/100
23/23 - 0s - 14ms/step - loss: 35.4427 - val_loss: 143.9144
Epoch 93/100
23/23 - 0s - 12ms/step - loss: 35.2484 - val_loss: 148.0443
Epoch 94/100
23/23 - 0s - 12ms/step - loss: 35.0283 - val_loss: 156.5646
Epoch 95/100
23/23 - 0s - 13ms/step - loss: 34.9013 - val_loss: 138.5522
Epoch 96/100
23/23 - 1s - 22ms/step - loss: 34.1865 - val_loss: 147.1839
Epoch 97/100
23/23 - 0s - 20ms/step - loss: 33.9831 - val_loss: 126.7201
Epoch 98/100
23/23 - 0s - 15ms/step - loss: 34.4635 - val_loss: 133.1449
Epoch 99/100
23/23 - 0s - 12ms/step - loss: 34.1516 - val_loss: 144.5722
Epoch 100/100
23/23 - 0s - 11ms/step - loss: 32.8977 - val_loss: 145.6771

<strong>You can refer to this [link](https://keras.io/models/sequential/) to learn about other functions that you can use for prediction or evaluation.</strong>

Feel free to vary the following and note what impact each change has on the model's performance:

1. Increase or decreate number of neurons in hidden layers
2. Add more hidden layers
3. Increase number of epochs

### Thank you for completing this lab!

This notebook was created by [Alex Aklson](https://www.linkedin.com/in/aklson/). I hope you found this lab interesting and educational. Feel free to contact me if you have any questions!

<!--
## Change Log

|  Date (YYYY-MM-DD) |  Version | Changed By  |  Change Description |
|---|---|---|---|
| 2024-11-20  | 3.0  | Aman  |  Updated the library versions to current |
| 2020-09-21  | 2.0  | Srishti  |  Migrated Lab to Markdown and added to course repo in GitLab |



<hr>

## <h3 align="center"> © IBM Corporation. All rights reserved. <h3/>

<hr>

Copyright &copy; [IBM Developer Skills Network](https://cognitiveclass.ai/?utm_source=bducopyrightlink&utm_medium=dswb&utm_campaign=bdu). This notebook and its source code are released under the terms of the [MIT License](https://opensource.org/license/mit).